name: planetarium
description: Solar System Simulator
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  equatable: ^2.0.5
  flex_color_picker: ^3.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  formz: ^0.6.1
  go_router: ^12.0.0
  google_fonts: ^6.1.0
  intl: ^0.18.1
  uuid: ^4.1.0
  window_manager: ^0.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  uses-material-design: true

flutter_launcher_icons:
  image_path: "assets/icon.png"
  windows:
    generate: true
